name: React Native CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Cache node_modules
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 4: Install Node dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Run unit tests
      - name: Run tests
        run: npm test

      # Step 6: Set up Java & Android SDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 7: Grant permission and build APK
      - name: Build debug APK
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleDebug

      # Step 8: Upload APK as GitHub artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

      # # Step 9 (Optional): Distribute via Firebase App Distribution
      # - name: Upload to Firebase App Distribution
      #   if: success() && github.event_name == 'push'
      #   uses: wzieba/Firebase-Distribution-Github-Action@v1
      #   with:
      #     appId: ${{ secrets.FIREBASE_APP_ID }}
      #     token: ${{ secrets.FIREBASE_TOKEN }}
      #     groups: testers
      #     file: android/app/build/outputs/apk/debug/app-debug.apk
